<?php
@session_start();

if(empty($_SESSION['token'])) {
    $token = md5(uniqid(rand(), TRUE));
    $_SESSION['token'] = $token;
}else{
    $token = $_SESSION['token'];
}
$enviado='no';

if(!empty($_POST['token'])){
	if($token==$_POST['token']){
		$subject="A new comment has been generated by the website";
		$cuerpo = '<p>A new comment has been generated by the website. ' . date('d-m-y h:i:s') . '</p>
		<table border="0">
		<tr><td><b>Name</b></td><td>' . $_POST["name"] . '</td></tr>
		<tr><td><b>Email</b></td><td>' . $_POST["email"] . '</td></tr>
		<tr><td><b>Phone number</b></td><td>' . $_POST["phone"] . '</td></tr>
		<tr><td><b>Comment</b></td><td>' . nl2br($_POST["comment"]) . '</td></tr>
		</table>';

		$email="reduque@hotmail.com";
		
		$headers = "MIME-Version: 1.0\n"; 
		$headers .= "Content-type: text/html; charset=utf-8\n"; 
		$headers .= "X-Priority: 3\n"; 
		$headers .= "X-MSmail-Priority: Normal\n"; 
		$headers .= "X-mailer: php\n"; 
		$headers .= "From: " . $email . "\n"; 



		//if($_SERVER['SERVER_NAME']<>"localhost") 
			mail($email, $subject, $cuerpo, $headers);

		$enviado='si';

	}
}

echo '{"enviado":"' . $enviado . '"}'

?>
